name: VyOS LTS ISO Builds

on:
  workflow_dispatch: {}
  push:
    tags:
      - '*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    container:
      image: vyos/vyos-build:equuleus
      env:
        TZ: Etc/UTC
      options: --privileged --sysctl net.ipv6.conf.lo.disable_ipv6=0

    steps:
    - name: Set release version
      run: |
        echo "RELEASE_VERSION=${GITHUB_REF:10}" >> $GITHUB_ENV

    - name: Clone source repository
      run: |
        git clone -b equuleus --single-branch https://github.com/vyos/vyos-build

    - name: Customize
      working-directory: vyos-build
      run: |
        ./configure \
        --architecture amd64 \
        --build-by "sagnik@ambyre.net" \
        --build-type release \
        --version ${{ env.RELEASE_VERSION }}

    - name: Build ISO
      working-directory: vyos-build
      run: |
        make iso

    - name: Create release
      id: create_release
      uses: actions/create-release@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: VyOS ${{ github.ref }} LTS
        body: |
          VyOS ${{ env.RELEASE_VERSION }} LTS
        draft: false
        prerelease: false

    - name: Upload ISO
      uses: actions/upload-release-asset@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: vyos-build/build/vyos-${{ env.RELEASE_VERSION }}-amd64.iso
        asset_name: vyos-${{ env.RELEASE_VERSION }}-amd64.iso
        asset_content_type: application/x-iso9660-image
