name: VyOS Equuleus LTS ISO Builds

on:
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    container:
      env:
        TZ: Etc/UTC
      image: vyos/vyos-build:equuleus
      options: --privileged --sysctl net.ipv6.conf.lo.disable_ipv6=0

    steps:
    - name: Set build version
      run: |
        echo "BUILD_VERSION=equuleus" >> $GITHUB_ENV
        
    - name: Set release version
      run: |        
        echo "RELEASE_VERSION=${{ env.BUILD_VERSION }}-$(date +%F_%H-%M)" >> $GITHUB_ENV 
     
    - name: Clone source repository
      run: |
        git clone -b ${{ env.BUILD_VERSION }} --single-branch https://github.com/vyos/vyos-build

    - name: Customize
      working-directory: vyos-build
      run: |
        ./configure \
        --architecture amd64 \
        --build-by "sagnik@ambyre.net" \
        --build-type release \
        --version ${{ env.RELEASE_VERSION }}

    - name: Build ISO
      working-directory: vyos-build
      run: |
        make iso

    - name: List artifacts
      run: |
        ls -lah
        ls -lah vyos-build/
        ls -lah vyos-build/build/

    - name: Create checksum and add to changelog
      run: |
        SHA256SUM=`sha256sum vyos-build/build/vyos-${{ env.RELEASE_VERSION }}-amd64.iso`
        echo -e "\n#### SHA256 Checksum\n\`\`\`\n$SHA256SUM\n" >> ./RELEASE_CHANGELOG
        echo -e "$SHA256SUM" > ./checksums.txt

    - name: Create release
      id: create_release
      uses: actions/create-release@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.RELEASE_VERSION }}
        release_name: VyOS ${{ env.RELEASE_VERSION }} LTS
        body: |
          VyOS ${{ env.RELEASE_VERSION }} LTS
        draft: false
        prerelease: false
        body_path: ./RELEASE_CHANGELOG

    - name: Upload ISO
      uses: actions/upload-release-asset@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: vyos-build/build/vyos-${{ env.RELEASE_VERSION }}-amd64.iso
        asset_name: vyos-${{ env.RELEASE_VERSION }}-amd64.iso
        asset_content_type: application/x-iso9660-image

    - name: Upload checksums
      uses: actions/upload-release-asset@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./checksums.txt
        asset_name: checksums.txt
        asset_content_type: text/plain
